# Framework Configuration
framework:
  charset:       UTF-8
  error_handler: null
  csrf_protection:
    enabled: true
    secret: xxxxxxxxxx
  router:        { resource: "%kernel.root_dir%/config/routing.yml" }
  validation:    { enabled: true, annotations: true }
  templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
  session:
    default_locale: en
    lifetime:       3600
    auto_start:     true
    name:           symfony

# Services
services:
  odm.repository.visit:
    public: true
    class: Doctrine\OdM\MongoDB\DocumentRepository
    factory_service: doctrine.odm.mongodb.app_document_manager
    factory_method: getRepository
    arguments:
      - VisitsBundle:Visit

# Twig Configuration
twig:
  debug:            %kernel.debug%
  strict_variables: %kernel.debug%

# Doctrine ODM Configuration
doctrine_mongo_db:
  auto_generate_hydrator_classes: true
  auto_generate_proxy_classes: true
  default_database: visits
  document_managers:
    app:
      mappings:
        VisitsBundle: {type: annotation}
  connections:
    app:
      server: "mongodb://visits:asdf@flame.mongohq.com:27030/visits"
      options:
        connect: true



## Swiftmailer Configuration
#swiftmailer:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx
