homepage:
  pattern:  /
  defaults: {_controller: VisitsBundle:Main:welcome}

register:
  pattern:  /register/{source}
  defaults: {_controller: VisitsBundle:Main:register}

stats:
  pattern:  /stats/{day}
  defaults: {_controller: VisitsBundle:Main:stats, day: now}
